---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name.transaction-enricher}
    username: ${spring.datasource.username.transaction-enricher}
    password: ${spring.datasource.password.transaction-enricher}
    url: ${spring.datasource.url.transaction-enricher}

backbase:
  communication:
    services:
      category:
        management:
          serviceId: "transaction-category-collector"
          serviceUrl: "/service-api/v2"
  transaction:
    enrichment:
      provider: mock
      mock:
        errorMode: false


