---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.arrangement-manager}
    password: ${spring.datasource.password.arrangement-manager}
    url: ${spring.datasource.url.arrangement-manager}

backbase:
  arrangement:
    masking:
      use-mask-indicator: false
    product-kinds:
      use-db: false
      kinds:
        # Current Account
        kind1:
          unmaskable-attributes:
            - IBAN
            - BBAN
            - number
        # Debit Card
        kind3:
          maskable-attributes:
            - IBAN
            - BBAN
            - number
        # Loan
        kind5:
          maskable-attributes:
            - IBAN
            - BBAN
            - number
          unmaskable-attributes:
            - IBAN
            - BBAN
            - number
        # Term Deposit
        kind6:
          maskable-attributes:
            - IBAN
            - BBAN
            - number
          unmaskable-attributes:
            - IBAN
            - BBAN
            - number
        # Investment Account
        kind7:
          maskable-attributes:
            - IBAN
            - BBAN
            - number
          unmaskable-attributes:
            - IBAN
            - BBAN
            - number
    pull-latest-balance: false
  security:
    mtls:
      enabled: false
    public:
      paths: "/integration-api/**"