spring:
  datasource:
    url: jdbc:mysql://localhost:3306/remote_config?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
buildingblocks:
  security:
    csrf:
      enabled: false