---
### Live profile
spring:
  profiles:
    active: live
    include: backbase_us_retail
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.payment-order-service}
    password: ${spring.datasource.password.payment-order-service}
    url: ${spring.datasource.url.payment-order-service}

backbase:
  payments:
    limits:
      enabled: false