---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name.transaction-manager}
    username: ${spring.datasource.username.transaction-manager}
    password: ${spring.datasource.password.transaction-manager}
    url: ${spring.datasource.url.transaction-manager}

backbase:
  enrichment:
    enabled: true
  security:
    mtls:
      enabled: false
    public:
      paths: "/integration-api/**"
  transaction:
    type: "ATM, ACH, Bill Payment, Cash, Credit/Debit Card, Check, Deposit, Fee, POS, Withdrawal"
    enrichment:
      enabled: true
  transactions:
    csv:
      export:
        dateFormat: "MM-dd-yyyy"
        fields: "BBAN,name,counterPartyAccountNumber,counterPartyName,currency,amount,creditDebitIndicator,bookingDate,type,typeGroup,reference,instructedCurrency,currencyExchangeRate,instructedAmount,description,category,checkSerialNumber"
        headers: "Account number(BBAN),Account name,Counter party account number,Counter party name,Currency,Amount,Credit/debit indicator,Book date,Transaction type,Transaction group,Transaction reference,Instructed currency,currency exchange rate,Instructed amount,Description,Category,Check number"
