version: '3.5'
services:
  remote-config-web-app:
    image: repo.backbase.com/backbase-docker-releases/remote-config-web-app:2022.11.1
    container_name: remote-config-web-app
    environment:
      - API_URL=http://localhost:7777/api
      - AUTH_CLIENT_ID=bb-web-client
      - AUTH_REALM=backbase
      - AUTH_URL=http://localhost:8180/auth
    ports:
      - '9191:8080'
